### ISSUE TITLE
`st.latex` doesn't work?

### ISSUE THREAD

**Issue by aghasemi** [whitphx/stlite#129] opened 2022-08-20 22:05 UTC
Hi,

Unless I'm doing something wrong, it seems `st.latex` doesn't work with stlite; it just prints the raw, un-rendered text. 

I managed to get some LaTeX rendered using MathJAX and `streamlit.components.v1.html`, but it is a bit limited in that one has to manually adjust the width and the height of the element for the size of the text, and dark/light themes are not applied.

Curious to know why doesn't `st.latex` work in the first place   :-/

Best

**Comment by whitphx** [comment] 2022-08-22 15:32
Can you provide an example that can reproduce the problem?

---

> but it is a bit limited in that one has to manually adjust the width and the height of the element for the size of the text

This is a separate problem, issued as #141.

>  and dark/light themes are not applied.

Can you provide the example of this too?

**Comment by aghasemi** [comment] 2022-08-22 21:22
> Can you provide an example that can reproduce the problem?

I tried simply the Streamlit example itself:

```
import streamlit as st
st.latex(r'''
     a + ar + a r^2 + a r^3 + \cdots + a r^{n-1} =
     \sum_{k=0}^{n-1} ar^k =
     a \left(\frac{1-r^{n}}{1-r}\right)
     ''')
```

> > but it is a bit limited in that one has to manually adjust the width and the height of the element for the size of the text
> 
> This is a separate problem, issued as #141.

Interesting, I thought it is just the way it is for all custom components created with the `html` method. How is the component size determined in general?

> > and dark/light themes are not applied.
> 
> Can you provide the example of this too?


```
import streamlit.components.v1 as components
import streamlit as st
 st.markdown('### LaTeX')
        _ = components.html(
            """
            <!DOCTYPE html>
            <html>
            <head>
            <title>MathJax TeX Test Page</title>
            <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
            <script type="text/javascript" id="MathJax-script" async
            src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
            </script>
            </head>
            <body>
            When \(a \ne 0\), there are two solutions to \(ax^2 + bx + c = 0\) and they are
            $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
            </body>
            </html>
        """,
            height=100,
            width=400,
        )
```

**Comment by whitphx** [comment] 2022-08-23 08:28
> I tried simply the Streamlit example itself:

That's weird. It successfully ran on the [playground app](https://whitphx.github.io/stlite/) as below.
<img width="432" alt="スクリーンショット 2022-08-23 17 12 11" src="https://user-images.githubusercontent.com/3135397/186107210-37ecfa30-de3e-4579-88b3-f6c6e63e9703.png">

Can you provide the full info to reproduce the problem?

>  I thought it is just the way it is for all custom components created with the html method. How is the component size determined in general?

Your understanding looks correct, and it is just not supported now on stlite -> Issued at #146

**Comment by aghasemi** [comment] 2022-08-25 12:15
The following code does not work for me running with `python3 -m http.server`:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Serverless STLite App</title>
  <meta name="description" content="A Serverless Streamlit application with OpenCV image processing that completely works on your browser">

  <script src="https://unpkg.com/ml5@latest/dist/ml5.min.js"></script>

</head>
<body>
  <div id="root"></div>
  <script src="https://whitphx.github.io/stlite/lib/mountable/stlite.js" ></script>
  <script>
    const loadPythonSource = async () => {
        //const pythonSource = await (await fetch("st_app.py") ).text()

        //pyodide.FS.writeFile("/hello.txt", "************", { encoding: "utf8" });

        stlite.mount({
        requirements: ["plotly","scipy"],
        entrypoint: "streamlit_app.py",  // The target file of the `streamlit run` command
        files: {
          "streamlit_app.py": `
import streamlit as st

st.latex(r"a^2+b^2=c^2")

          `
        }
      }
        ,document.getElementById("root")
        )
    }
    window.onload = loadPythonSource

  </script>
</body>
</html>
```

**Comment by whitphx** [comment] 2022-08-26 16:26
Oh, I see, it does not work with the `<script>`-loaded version. Thanks.

It's probably due to #155, which I will work on.

**Comment by whitphx** [comment] 2022-08-28 14:14
It's fixed now. Please update your code following the current README.md where the URL of `stlite.js` has been updated and the `<link>` tag loading a CSS file has been added.)

See, the following example renders the LaTeX component properly.
This example is just copy-and-pasted from the [official doc](https://docs.streamlit.io/library/api-reference/text/st.latex), but note that `\` (backquote) is replaced with `\\` (double backquote) because it is considered as an escape character inside JS template literals.

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>stlite app</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@stlite/mountable@0.3.0/build/stlite.css"
    />
  </head>
  <body>
    <div id="root"></div>
    <script src="https://cdn.jsdelivr.net/npm/@stlite/mountable@0.3.0/build/stlite.js"></script>
    <script>
      stlite.mount(
        `
import streamlit as st

st.latex(r'''
     a + ar + a r^2 + a r^3 + \\cdots + a r^{n-1} =
     \\sum_{k=0}^{n-1} ar^k =
     a \\left(\\frac{1-r^{n}}{1-r}\\right)
     ''')
`,
        document.getElementById("root")
      );
    </script>
  </body>
</html>

```
<img width="664" alt="スクリーンショット 2022-08-28 23 12 14" src="https://user-images.githubusercontent.com/3135397/187078229-571ce768-5e25-4a1b-a30e-1b77fe46a2ed.png">

**Closed** 2022-08-30 03:42 UTC
